// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZWbUNQE7srsByGj4US_anDhEWMGXwhzM',
    appId: '1:805610142626:web:b61f314c9224933ca150fb',
    messagingSenderId: '805610142626',
    projectId: 'rmhconnect-a5adb',
    authDomain: 'rmhconnect-a5adb.firebaseapp.com',
    storageBucket: 'rmhconnect-a5adb.firebasestorage.app',
    measurementId: 'G-5BLQV0DY1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCW49uSPdImyDFTXPptQWGxXtLqUzhbQA',
    appId: '1:805610142626:android:ca89a3d5e110b355a150fb',
    messagingSenderId: '805610142626',
    projectId: 'rmhconnect-a5adb',
    storageBucket: 'rmhconnect-a5adb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvnZQqY_a3QxFt16pgsLXoSUXNgUD3nBo',
    appId: '1:805610142626:ios:53c92b7494d9451ea150fb',
    messagingSenderId: '805610142626',
    projectId: 'rmhconnect-a5adb',
    storageBucket: 'rmhconnect-a5adb.firebasestorage.app',
    iosBundleId: 'com.example.rmhconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvnZQqY_a3QxFt16pgsLXoSUXNgUD3nBo',
    appId: '1:805610142626:ios:53c92b7494d9451ea150fb',
    messagingSenderId: '805610142626',
    projectId: 'rmhconnect-a5adb',
    storageBucket: 'rmhconnect-a5adb.firebasestorage.app',
    iosBundleId: 'com.example.rmhconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZWbUNQE7srsByGj4US_anDhEWMGXwhzM',
    appId: '1:805610142626:web:1f5670d97e3d4431a150fb',
    messagingSenderId: '805610142626',
    projectId: 'rmhconnect-a5adb',
    authDomain: 'rmhconnect-a5adb.firebaseapp.com',
    storageBucket: 'rmhconnect-a5adb.firebasestorage.app',
    measurementId: 'G-DCBXV3CGVE',
  );
}
