// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG36tq6JZojP7gGBJ3gxRZl_APZT8vHOw',
    appId: '1:555187148749:web:0f58c711367fbdc49f1684',
    messagingSenderId: '555187148749',
    projectId: 'rhmc-connect',
    authDomain: 'rhmc-connect.firebaseapp.com',
    storageBucket: 'rhmc-connect.firebasestorage.app',
    measurementId: 'G-3XSCM5VPP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDar7xReuvYkKfBu9e_Uk-uHWSTp3raFzM',
    appId: '1:555187148749:android:600b08ed4474b1de9f1684',
    messagingSenderId: '555187148749',
    projectId: 'rhmc-connect',
    storageBucket: 'rhmc-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxPTe-R_EW4ncEoMafxEhnhaFD64OgU_I',
    appId: '1:555187148749:ios:9328defbd03828a69f1684',
    messagingSenderId: '555187148749',
    projectId: 'rhmc-connect',
    storageBucket: 'rhmc-connect.firebasestorage.app',
    iosBundleId: 'com.example.rmhconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxPTe-R_EW4ncEoMafxEhnhaFD64OgU_I',
    appId: '1:555187148749:ios:9328defbd03828a69f1684',
    messagingSenderId: '555187148749',
    projectId: 'rhmc-connect',
    storageBucket: 'rhmc-connect.firebasestorage.app',
    iosBundleId: 'com.example.rmhconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG36tq6JZojP7gGBJ3gxRZl_APZT8vHOw',
    appId: '1:555187148749:web:a2bd500a07002aaa9f1684',
    messagingSenderId: '555187148749',
    projectId: 'rhmc-connect',
    authDomain: 'rhmc-connect.firebaseapp.com',
    storageBucket: 'rhmc-connect.firebasestorage.app',
    measurementId: 'G-8ZP4VMLPY1',
  );

}